DELETE http://localhost:8089/events/1/registrations
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyNkBleGFtcGxlLmNvbSIsImV4cCI6MTc1OTkxODc3NiwidXNlcklEIjoyfQ.5Z_hsCoIWFI9nigzHsqQKapAoGy1Iv1w9TnRBVrh5lw
