DELETE http://localhost:8089/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYwODcxNjYxLCJ1c2VySUQiOjF9.bvG3AkTfbRaZeO-38OBhHaafV0-8hcRVo58qzzzMEzo