POST http://localhost:8089/events/3/registrations
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYwODc1NDIyLCJ1c2VySUQiOjF9.4zSo71idW5PyKjVsjFW9o5O6ipAX0-MISd4R5YDn5Kg
