PUT http://localhost:8089/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYwODcxNjYxLCJ1c2VySUQiOjF9.bvG3AkTfbRaZeO-38OBhHaafV0-8hcRVo58qzzzMEzo

{
    "name": "Updated Event",
    "description": "This is an updated event again!",
    "location": "Updated Location",
    "date_time": "2023-10-10T10:00:00Z"
}